import { Button as ButtonPrimitive } from "@base-ui/react/button";
import { cva } from "class-variance-authority";

import { cn } from "@/lib/utils";

/**
 * The pill button from the designs.
 *
 * Hand-authored design primitive, deliberately separate from
 * `components/ui/button.jsx` — that file is regenerated by the shadcn CLI and
 * any edit would be overwritten (TASTE.md §6.2). The PascalCase filename
 * matches Text.jsx / Box.jsx and guarantees the CLI will never claim it.
 *
 * To render as a link, use Base UI's `render` prop — there is no `asChild` in
 * Base UI:
 *   <CtaButton render={<Link href="/contact" />}>Talk to us</CtaButton>
 */
const ctaButtonVariants = cva(
  "inline-flex cursor-pointer items-center justify-center gap-[9px] rounded-full font-body font-semibold whitespace-nowrap transition-[transform,box-shadow,border-color,background-color] duration-200 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-navy disabled:pointer-events-none disabled:opacity-50",
  {
    variants: {
      variant: {
        primary:
          "bg-navy text-lime hover:-translate-y-0.5 hover:shadow-[0_14px_30px_-12px_rgba(10,22,40,0.5)]",
        ghost:
          "border border-ink/22 bg-transparent text-ink hover:border-navy hover:bg-ink/[0.04]",
      },
      size: {
        default: "px-7 py-4 text-sm",
        sm: "px-[22px] py-3 text-[13px]",
      },
      block: {
        true: "w-full",
        false: "",
      },
    },
    defaultVariants: {
      variant: "primary",
      size: "default",
      block: false,
    },
  }
);

function CtaButton({ className, variant, size, block, ...props }) {
  return (
    <ButtonPrimitive
      data-slot="cta-button"
      className={cn(ctaButtonVariants({ variant, size, block }), className)}
      {...props}
    />
  );
}

export { CtaButton, ctaButtonVariants };
export default CtaButton;
